name: Replace-With-Your-Action-Name
description: Replace-With-Your-Action-Description
inputs:
  path_dockerfile:
    description: "Path to dockerfile"
    required: false
    default: "Dockerfile"
  image_name:
    description: "Specifies the name for the generated Docker image"
    required: true
    default: ""
  tag_name:
    description: "Specifies the tag to be added to the final image."
    required: false
    default: ""
runs:
  using: composite
  steps:
    - run: |
        
        if [ -z "${{ inputs.replace_with_input_name }}" ]; then
        export TAG=$(date +%s)
        else
        export TAG="${{ inputs.replace_with_input_name }}"
        fi
        
        docker build . --file ${{inputs.path_dockerfile}} --tag ${{TAG}}:$(date +%s)
        docker image ls
      shell: bash
